// This file is auto-generated by the Supabase CLI.
// Do not edit manually. Run `npm run gen:types` to regenerate.
//
// Command: npx supabase gen types typescript --project-id <project-id> --schema public > src/types/database.ts
//
// This will be populated once the database schema is created and linked to a remote project.

export type Database = Record<string, never>;
