import { ShieldCheck } from "lucide-react";
import { TabbyMascot, type MascotVariant } from "@/components/branding/TabbyMascot";
import type { Severity } from "../types";

interface AIAnalysisCardProps {
  condition: string;
  confidence: number;
  reasoning: string;
  firstAid: string[];
  severity: Severity;
}

function getMascotVariant(severity: Severity): MascotVariant {
  switch (severity) {
    case "CRITICAL":
    case "HIGH":
      return "warning";
    case "MEDIUM":
      return "think";
    case "LOW":
    default:
      return "happy";
  }
}

/**
 * AIAnalysisCard — displays AI triage results.
 * Centered mascot + condition + confidence at top.
 * Left-aligned reasoning, first aid, disclaimer below.
 * Mascot variant depends on severity.
 */
export function AIAnalysisCard({ condition, confidence, reasoning, firstAid, severity }: AIAnalysisCardProps) {
  const confColor = confidence >= 85 ? "text-emerald-600 bg-emerald-50 border-emerald-200" :
                    confidence >= 70 ? "text-amber-600 bg-amber-50 border-amber-200" :
                    "text-red-600 bg-red-50 border-red-200";

  const mascotVariant = getMascotVariant(severity);

  return (
    <div className="rounded-[16px] border border-[#A788FA]/15 bg-white p-5 sm:p-6 shadow-[0_4px_20px_rgba(108,92,231,0.08)]">
      {/* Compact header: mascot + condition/confidence banner */}
      <div className="flex items-center gap-4 mb-5 pb-4 border-b border-[#A788FA]/10">
        <TabbyMascot variant={mascotVariant} size="md" className="shrink-0" />
        <div className="flex-1 min-w-0">
          <p className="text-[10px] font-bold text-[#6C5CE7]/70 uppercase tracking-wider mb-0.5">AI Analysis</p>
          <h3 className="text-base font-bold text-[#2D3748] truncate">{condition}</h3>
          <div className="flex items-center gap-2 mt-1.5">
            <span className={`rounded-full border px-2.5 py-0.5 text-[10px] font-semibold ${confColor}`}>
              {confidence}% confidence
            </span>
            <span className={`rounded-full border px-2 py-0.5 text-[9px] font-bold uppercase tracking-wide bg-[#6C5CE7]/5 border-[#A788FA]/15 text-[#6C5CE7]`}>
              AI · Not a diagnosis
            </span>
          </div>
        </div>
      </div>

      {/* Left-aligned details */}
      <div className="space-y-4">
        <div>
          <p className="text-[10px] font-bold text-[#2D3748]/50 uppercase tracking-wider mb-1.5">Reasoning</p>
          <p className="text-sm text-[#2D3748]/80 leading-relaxed">{reasoning}</p>
        </div>
        {firstAid.length > 0 && (
          <div>
            <p className="text-[10px] font-bold text-[#2D3748]/50 uppercase tracking-wider mb-2">First Aid Guidance</p>
            <ol className="space-y-2">
              {firstAid.map((tip, i) => (
                <li key={i} className="flex items-start gap-2.5 text-sm text-[#2D3748]/80">
                  <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#6C5CE7]/10 text-[10px] font-bold text-[#6C5CE7]">{i + 1}</span>
                  {tip}
                </li>
              ))}
            </ol>
          </div>
        )}
      </div>

      {/* Disclaimer */}
      <div className="mt-5 rounded-[10px] bg-[#A788FA]/5 p-3">
        <p className="flex items-start gap-1.5 text-[11px] text-[#6C5CE7]">
          <ShieldCheck size={12} strokeWidth={1.5} className="mt-0.5 shrink-0" />
          Generated by AI. Not a medical diagnosis. Final decisions belong to verified veterinarians.
        </p>
      </div>
    </div>
  );
}
