import { ShieldCheck } from "lucide-react";
import { TabbyMascot, type MascotVariant } from "@/components/branding/TabbyMascot";
import type { Severity } from "../types";

interface AIAnalysisCardProps {
  condition: string;
  confidence: number;
  reasoning: string;
  firstAid: string[];
  severity: Severity;
}

function getMascotVariant(severity: Severity): MascotVariant {
  switch (severity) {
    case "CRITICAL":
    case "HIGH":
      return "warning";
    case "MEDIUM":
      return "think";
    case "LOW":
    default:
      return "happy";
  }
}

/**
 * AIAnalysisCard — displays AI triage results.
 * Centered mascot + condition + confidence at top.
 * Left-aligned reasoning, first aid, disclaimer below.
 * Mascot variant depends on severity.
 */
export function AIAnalysisCard({ condition, confidence, reasoning, firstAid, severity }: AIAnalysisCardProps) {
  const confColor = confidence >= 85 ? "text-emerald-600 bg-emerald-50 border-emerald-200" :
                    confidence >= 70 ? "text-amber-600 bg-amber-50 border-amber-200" :
                    "text-red-600 bg-red-50 border-red-200";

  const mascotVariant = getMascotVariant(severity);

  return (
    <div className="rounded-[16px] border border-[#A788FA]/15 bg-white p-5 sm:p-6 shadow-[0_4px_20px_rgba(108,92,231,0.08)]">
      {/* Centered header: mascot + condition + confidence */}
      <div className="flex flex-col items-center text-center mb-6">
        <TabbyMascot variant={mascotVariant} size="xl" />
        <h3 className="mt-3 font-heading text-base font-semibold text-[#2D3748]">AI Analysis</h3>
        <p className="mt-1 text-xl font-bold text-[#2D3748]">{condition}</p>
        <span className={`mt-2 rounded-full border px-3 py-0.5 text-xs font-semibold ${confColor}`}>
          Confidence: {confidence}%
        </span>
      </div>

      {/* Left-aligned details */}
      <div className="space-y-4">
        <div>
          <p className="text-xs font-medium text-[#2D3748]/60 mb-1">Reasoning</p>
          <p className="text-sm text-[#2D3748]/80 leading-relaxed">{reasoning}</p>
        </div>
        <div>
          <p className="text-xs font-medium text-[#2D3748]/60 mb-2">First Aid Guidance</p>
          <ul className="space-y-2">
            {firstAid.map((tip, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-[#2D3748]/80">
                <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#6C5CE7]" />
                {tip}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="mt-5 rounded-[10px] bg-[#A788FA]/5 p-3">
        <p className="flex items-start gap-1.5 text-[11px] text-[#6C5CE7]">
          <ShieldCheck size={12} strokeWidth={1.5} className="mt-0.5 shrink-0" />
          Generated by AI. Not a medical diagnosis. Final decisions belong to verified veterinarians.
        </p>
      </div>
    </div>
  );
}
